Fix PR5633 by making the preprocessor handle the case where we can stat a file but where mmaping it fails.  In this case, we emit an error like: t.c:1:10: fatal error: error opening file '../../foo.h'
instead of "cannot find file".

llvm-svn=90110